name: Bench

on:
  workflow_dispatch:
    inputs:
      filter:
        description: 'benchmark filter'
        required: false
        default: ''

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: Bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --all -- ${{ github.event.inputs.filter }}
