name: Build

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Init Cache
       uses: actions/cache@v2
       with:
         path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
     - name: Install Toolchain
       uses: actions-rs/toolchain@v1
       with:
         toolchain: stable
         override: true
         default: true
     - name: Test
       uses: actions-rs/cargo@v1
       with:
         command: test
         args: --all
